# Generated by Django 3.0.3 on 2020-03-08 16:29

import datetime
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AirCompany',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=10, verbose_name='Nome')),
            ],
            options={
                'verbose_name_plural': 'Companhias',
            },
        ),
        migrations.CreateModel(
            name='Airport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('airport_name', models.CharField(max_length=200, verbose_name='Aeroporto')),
                ('airport_city', models.CharField(max_length=200, verbose_name='Cidade')),
                ('airport_country', models.CharField(max_length=200, verbose_name='País')),
            ],
            options={
                'verbose_name_plural': 'Aeroportos',
            },
        ),
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=200, verbose_name='Morada')),
                ('nif', models.CharField(max_length=9, null=True, unique=True, validators=[django.core.validators.RegexValidator('^\\d{1,10}$')], verbose_name='NIF')),
                ('mobile', models.CharField(max_length=9, validators=[django.core.validators.RegexValidator('^\\d{1,10}$')], verbose_name='Telemóvel')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Clientes',
            },
        ),
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(blank=True, default=datetime.datetime.now, verbose_name='Data')),
                ('flight_id', models.CharField(max_length=10, verbose_name='Ref. Voo')),
                ('airport', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.Airport', verbose_name='Aeroporto')),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.AirCompany', verbose_name='Companhia')),
            ],
            options={
                'verbose_name_plural': 'Voos',
            },
        ),
        migrations.CreateModel(
            name='Hotels',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hotel_name', models.CharField(max_length=30, verbose_name='Nome')),
                ('address', models.CharField(max_length=30, verbose_name='Morada')),
                ('city', models.CharField(max_length=10, verbose_name='Cidade')),
                ('mobile', models.CharField(max_length=9, validators=[django.core.validators.RegexValidator('^\\d{1,10}$')], verbose_name='Telemóvel')),
            ],
            options={
                'verbose_name_plural': 'Hotéis',
            },
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trip_id', models.CharField(max_length=20, verbose_name='Ref. Viagem')),
                ('destination', models.CharField(max_length=200, null=True, verbose_name='Destino')),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.Clients', verbose_name='Cliente')),
                ('hotel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.Hotels', verbose_name='Hotel')),
                ('in_flight', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inbound_flight', to='backend.Flight', verbose_name='Voo Regresso')),
                ('out_flight', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='outbound_flight', to='backend.Flight', verbose_name='Voo Ida')),
            ],
            options={
                'verbose_name_plural': 'Viagens',
            },
        ),
    ]
