# Generated by Django 3.0.3 on 2020-03-10 16:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='in_flight',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inbound_flight', to='backend.Flight', verbose_name='Voo Regresso'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='out_flight',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='outbound_flight', to='backend.Flight', verbose_name='Voo Ida'),
        ),
    ]
