# Generated by Django 3.0.3 on 2020-03-10 16:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_auto_20200310_1643'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='out_flight',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='outbound_flight', to='backend.Flight', verbose_name='Voo Ida'),
        ),
    ]
