# Generated by Django 3.0.3 on 2020-03-10 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_auto_20200310_1645'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='trip_id',
            field=models.CharField(max_length=20, unique=True, verbose_name='Ref. Viagem'),
        ),
    ]
