# Generated by Django 3.0.3 on 2020-03-11 12:07

import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_auto_20200310_1646'),
    ]

    operations = [
        migrations.AddField(
            model_name='clients',
            name='city',
            field=models.CharField(default=django.utils.timezone.now, max_length=200, verbose_name='Cidade'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='clients',
            name='postal',
            field=models.CharField(default=3971, max_length=7, validators=[django.core.validators.RegexValidator('^\\\\d{4}-\\\\d{3}$')], verbose_name='Código Postal'),
            preserve_default=False,
        ),
    ]
