# Generated by Django 3.0.3 on 2020-03-11 12:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_auto_20200311_1208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clients',
            name='postal',
            field=models.CharField(max_length=8, validators=[django.core.validators.RegexValidator('^\\d{4}(-\\d{3})?$')], verbose_name='Código Postal'),
        ),
    ]
