# Generated by Django 3.0.3 on 2020-03-14 19:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_auto_20200311_1210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='hotel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.Hotels', verbose_name='Hotel'),
        ),
    ]
